DEVSTATE_DISCONNECTED = 0
DEVSTATE_DISCONNECTING = 2
DEVSTATE_CONNECTING = 5
DEVSTATE_CONNECTED = 1
DEVSTATE_ONLINE = 3
DEVSTATE_DPAUSE = 4
DEVSTATE_UNINIT = 6
DEVSTATE_SEARCHING = 7
DEVSTATE_INVALIDSTEP = 8

DEVREASON_REQUESTED = 20
DEVREASON_STATECHANGE = 21
DEVREASON_SIMULATOR = 22
DEVREASON_PREPARE_ERROR = 23
DEVREASON_OPERATION_ERROR = 24
DEVREASON_TIMEOUT = 25
DEVREASON_BLE_DISABLED = 26


MSG_CONNECTION_STATE_INVALID = 'Please disconnect all devices before'
MSG_TYPE_DEVICE_UNKNOWN = 'Unknown device type'
MSG_INVALID_VIEW = 'Invalid view'
MSG_INVALID_USER = 'Invalid user'
MSG_INVALID_ITEM = 'Invalid DB item'
MSG_DB_SAVE_ERROR = 'Cannot save to database %s'
MSG_COMMAND_TIMEOUT = 'Timeout waiting for command response'
MSG_OK = 'OK'
MSG_ERROR = 'Generic error'
CONFIRM_OK = 0
CONFIRM_FAILED_1 = -1
CONFIRM_FAILED_2 = -2
CONFIRM_FAILED_3 = -10

DI_FIRMWARE = 'info_firmware'
DI_BLNANE = 'info_blname'
DI_SOFTWARE = 'info_software'
DI_SYSTEMID = 'info_systemid'

COMMAND_SEARCH = '/device_search'
COMMAND_DEVICEFOUND = '/device_found'
COMMAND_CONNECT = '/view_connect'
COMMAND_DISCONNECT = '/view_disconnect'
COMMAND_STOPSEARCH = '/device_stopsearch'
COMMAND_SAVEDEVICE = '/device_save'
COMMAND_DELDEVICE = '/device_del'
COMMAND_NEWSESSION = '/device_session'
COMMAND_DEVICESTATE = '/device_state'
COMMAND_DEVICEFIT = '/device_fit'
COMMAND_NEWDEVICE = '/newdevice'
COMMAND_STOP = '/stop'
COMMAND_PING = '/ping'
COMMAND_CONFIRM = '/confirm'
COMMAND_LISTDEVICES = '/listdevices'
COMMAND_LISTDEVICES_RV = '/listdevices_rv'
COMMAND_LISTUSERS = '/listusers'
COMMAND_LISTUSERS_RV = '/listusers_rv'
COMMAND_LISTVIEWS = '/listviews'
COMMAND_LISTVIEWS_RV = '/listviews_rv'
COMMAND_SAVEVIEW = '/saveview'
COMMAND_DELVIEW = '/delview'
COMMAND_SAVEUSER = '/saveuser'
COMMAND_DELUSER = '/deluser'

COMMAND_WBD_CHARACTERISTICCHANGED = '/wbd_characteristic_changed'
COMMAND_WBD_CHARACTERISTICREAD = '/wbd_characteristic_read'
COMMAND_WBD_CHARACTERISTICWRITTEN = '/wbd_characteristic_written'
COMMAND_WBD_CONNECTGATT = '/wbd_connectgatt'
COMMAND_WBD_CONNECTSTATECHANGE = '/wbd_connectstatechange'
COMMAND_WBD_DESCRIPTORREAD = '/wbd_descriptorread'
COMMAND_WBD_DESCRIPTORWRITTEN = '/wbd_descriptorwritten'
COMMAND_WBD_DEVICEFOUND = '/wbd_devicefound'
COMMAND_WBD_DISCONNECTGATT = '/wbd_disconnectgatt'
COMMAND_WBD_DISCOVERSERVICES = '/wbd_discoverservices'
COMMAND_WBD_ENABLENOT = '/wbd_enablenot'
COMMAND_WBD_GATTRELEASE = '/wbd_gattrelease'
COMMAND_WBD_READCHARACTERISTIC = '/wbd_readcharacteristic'
COMMAND_WBD_SERVICES = '/wbd_services'
COMMAND_WBD_STARTSCAN = '/wbd_startscan'
COMMAND_WBD_STOPSCAN = '/wbd_stopscan'
COMMAND_WBD_STOPSCAN_RV = '/wbd_stopscan_rv'
COMMAND_WBD_WRITECHARACTERISTIC = '/wbd_writecharacteristic'
COMMAND_WBD_WRITEDESCRIPTOR = '/wbd_writedescriptor'
